Repository networkupstools/wmnut, pull requests merged in 2025-04, with the labels that each got.

#15 README.asciidoc: update link to latest release
  README.asciidoc
Labels: documentation

#18 Potential fix for code scanning alert no. 35: Unbounded write
  configure.ac
  src/rcfiles.c
Labels: bug

#17 Potential fix for code scanning alert no. 36: Unbounded write
  src/wmnut.c
Labels: bug

#19 Fix Ups_list iteration and "rootwin" naming
  src/wmgeneral.c
  src/wmnut.c
  src/wmnut.h
Labels: bug

#16 Potential fix for code scanning alert no. 37: Local variable hides global variable
  src/wmgeneral.c
Labels: bug

#20 Introduce NUT_PATH_MAX and revise array limit/sizeof where numbers were used
  configure.ac
  src/Makefile.am
  src/rcfiles.c
  src/wmgeneral.h
  src/wmnut-common.h
  src/wmnut.c
  src/wmnut.h
Labels: bug, enhancement

#21 Use `xmalloc()` where available (for extra error checks)
  configure.ac
  src/rcfiles.c
  src/wmnut.c
Labels: enhancement

#22 src/wmnut.c: CleanHosts(): free upsname/hostname strings if set
  src/rcfiles.c
  src/wmgeneral.h
  src/wmnut.c
Labels: enhancement
